Name: Ishita Kaundal             
Roll no.: 102017184

In [2]:
import numpy as np
import pandas as pd

In [3]:
url = 'https://raw.githubusercontent.com/AnjulaMehto/Sampling_Assignment/main/Creditcard_data.csv'
data = pd.read_csv(url)
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,1
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
class_freq = data['Class'].value_counts()
print(f"Number of classes: {len(class_freq)}")
print("Class frequencies:")
print(class_freq)

Number of classes: 2
Class frequencies:
0    763
1      9
Name: Class, dtype: int64

In [5]:
#Converting the dataset into balanced dataset

from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler

# Separate features and target
x = data.drop('Class', axis=1)
y = data['Class']

# Instantiate oversampler and undersampler
oversampler = RandomOverSampler()
undersampler = RandomUnderSampler()

# Resample using both oversampling and undersampling
x_over, y_over = oversampler.fit_resample(x, y)
x_resampled, y_resampled = undersampler.fit_resample(x_over, y_over)

# Print the number of samples in each class
print("Number of samples in each class after resampling:")
print(y_resampled.value_counts())

Number of samples in each class after resampling:
0    763
1    763
Name: Class, dtype: int64

In [6]:
x_resampled

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62
1,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66
2,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50
3,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99
4,2,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,...,0.084968,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1521,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69
1522,484,-0.928088,0.398194,1.741131,0.182673,0.966387,-0.901004,0.879016,-0.156590,-0.142117,...,-0.118283,0.066353,0.281378,-0.257966,0.385384,0.391117,-0.453853,-0.104448,-0.125765,1.00
1523,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69
1524,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69
1525,539,-1.738582,0.052740,1.187057,-0.656652,0.920623,-0.291788,0.269083,0.140631,0.023464,...,0.002974,-0.179545,-0.192036,-0.261879,-0.237477,-0.335040,0.240323,-0.345129,-0.383563,1.00

In [7]:
new_data = pd.concat([x_resampled, y_resampled], axis=1)
new_data

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
2,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
3,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
4,2,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,...,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1521,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,1
1522,484,-0.928088,0.398194,1.741131,0.182673,0.966387,-0.901004,0.879016,-0.156590,-0.142117,...,0.066353,0.281378,-0.257966,0.385384,0.391117,-0.453853,-0.104448,-0.125765,1.00,1
1523,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,1
1524,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,1
1525,539,-1.738582,0.052740,1.187057,-0.656652,0.920623,-0.291788,0.269083,0.140631,0.023464,...,-0.179545,-0.192036,-0.261879,-0.237477,-0.335040,0.240323,-0.345129,-0.383563,1.00,1

In [8]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

Sampling the data in the next few cells using different sampling techniques.

In [9]:
#1

# Simple random sampling
n1 = int((1.96*1.96 * 0.5*0.5)/(0.05**2))
random_sample = new_data.sample(n=n1, random_state=42)
print(random_sample)

      Time        V1        V2        V3        V4        V5        V6  \
1439   574  1.257719  0.364739  0.306923  0.690638 -0.357792 -1.067481
76      49  0.921544 -0.067084  0.077461  0.953638  0.067412  0.016152
1010   164  0.073497  0.551033  0.451890  0.114964  0.822947  0.251480
660    503  0.074738 -3.032009 -0.429919 -0.442721 -1.784710 -0.066668
1132   574  1.257719  0.364739  0.306923  0.690638 -0.357792 -1.067481
...    ...       ...       ...       ...       ...       ...       ...
1481   574  1.257719  0.364739  0.306923  0.690638 -0.357792 -1.067481
756    574 -1.062129 -0.618574  0.615388 -3.335834  0.746649 -0.540531
1074   472 -3.043541 -3.157307  1.088463  2.288644  1.359805 -1.064823
867    574  1.257719  0.364739  0.306923  0.690638 -0.357792 -1.067481
485    358  1.106251  0.398625  0.860421  2.388862 -0.365843 -0.192568

            V7        V8        V9  ...       V21       V22       V23  \
1439  0.094272 -0.210300  0.014455  ... -0.286856 -0.820658  0.127663
76    0.320452  0.038534 -0.391513  ... -0.333930 -1.299920  0.084311
1010  0.296319  0.139497 -0.123050  ... -0.128758 -0.381932  0.151012
660   0.098736 -0.222525 -0.241858  ... -0.078927 -1.247242 -0.620402
1132  0.094272 -0.210300  0.014455  ... -0.286856 -0.820658  0.127663
...        ...       ...       ...  ...       ...       ...       ...
1481  0.094272 -0.210300  0.014455  ... -0.286856 -0.820658  0.127663
756   0.705932  0.032525  1.334181  ... -0.114269 -0.661122  0.136250
1074  0.325574 -0.067794 -0.270953  ...  0.661696  0.435477  1.375966
867   0.094272 -0.210300  0.014455  ... -0.286856 -0.820658  0.127663
485  -0.121769  0.150876 -0.733271  ... -0.253189 -0.952836  0.181643

           V24       V25       V26       V27       V28  Amount  Class
1439  0.343128  0.221120  0.094391 -0.022189  0.030944    1.29      1
76   -0.370398  0.155102 -0.834490  0.000909  0.035547  135.51      0
1010 -1.363967 -1.389079  0.075412  0.231750  0.230171    0.99      1
660  -0.368545 -0.073359  1.296835 -0.192760  0.121440  712.82      0
1132  0.343128  0.221120  0.094391 -0.022189  0.030944    1.29      1
...        ...       ...       ...       ...       ...     ...    ...
1481  0.343128  0.221120  0.094391 -0.022189  0.030944    1.29      1
756  -1.377245  0.263820 -1.115516  0.079213  0.116638  131.37      0
1074 -0.293803  0.279798 -0.145362 -0.252773  0.035764  529.00      1
867   0.343128  0.221120  0.094391 -0.022189  0.030944    1.29      1
485   0.222462  0.083552 -0.342278 -0.017021  0.020976   17.43      0

[384 rows x 31 columns]

In [10]:
#2

# Systematic sampling
interval = 2
n2 = (1.96**2 * 0.5 * (1-0.5)) / 0.05**2
systematic_sample = new_data.iloc[::interval]
systematic_sample

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
2,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,...,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0
6,7,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,...,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,40.80,0
8,9,-0.338262,1.119593,1.044367,-0.222187,0.499361,-0.246761,0.651583,0.069539,-0.736727,...,-0.246914,-0.633753,-0.120794,-0.385050,-0.069733,0.094199,0.246219,0.083076,3.68,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1516,406,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1
1518,539,-1.738582,0.052740,1.187057,-0.656652,0.920623,-0.291788,0.269083,0.140631,0.023464,...,-0.179545,-0.192036,-0.261879,-0.237477,-0.335040,0.240323,-0.345129,-0.383563,1.00,1
1520,574,1.257719,0.364739,0.306923,0.690638,-0.357792,-1.067481,0.094272,-0.210300,0.014455,...,-0.286856,-0.820658,0.127663,0.343128,0.221120,0.094391,-0.022189,0.030944,1.29,1
1522,484,-0.928088,0.398194,1.741131,0.182673,0.966387,-0.901004,0.879016,-0.156590,-0.142117,...,0.066353,0.281378,-0.257966,0.385384,0.391117,-0.453853,-0.104448,-0.125765,1.00,1
1524,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,1

In [12]:
#3

# Stratified sampling
n3 = int((1.96**2 * 0.5*0.5)/((0.05)**2))
strata = new_data.groupby('Class')

# Sample 2 rows from each stratum
stratified_sample = strata.apply(lambda x: x.sample(n3))
stratified_sample

            Time        V1        V2        V3        V4        V5        V6  \
Class
0     211    140  1.007947 -1.289492  0.666741 -0.741321 -1.290523  0.302172
      446    327  1.162687  0.269139  0.163258  0.943088 -0.003225 -0.421822
      732    556 -0.848087 -0.573441  1.491399 -1.739997  0.411572  1.453712
      757    574  1.178364  0.444453 -0.398723  0.724486  0.123439 -0.753883
      66      44 -0.948896  0.248414  2.956914  2.813750  0.145539 -0.027353
...          ...       ...       ...       ...       ...       ...       ...
1     776    484 -0.928088  0.398194  1.741131  0.182673  0.966387 -0.901004
      1129   539 -1.738582  0.052740  1.187057 -0.656652  0.920623 -0.291788
      905    406 -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545
      896    118  1.254914  0.350287  0.302488  0.693114 -0.371470 -1.070256
      1390   164  0.073497  0.551033  0.451890  0.114964  0.822947  0.251480

                  V7        V8        V9  ...       V21       V22       V23  \
Class                                     ...
0     211  -1.026907  0.220562 -0.607465  ...  0.530549  1.113561 -0.260042
      446   0.213395 -0.125542 -0.396783  ...  0.087745  0.236577 -0.191415
      732   0.815613 -0.175546  0.573243  ... -0.016864  0.439242 -0.380274
      757   0.161412  0.004017 -0.306011  ... -0.055267 -0.147937 -0.026551
      66    0.133702 -0.307535 -0.125244  ... -0.083647  0.416090  0.207537
...              ...       ...       ...  ...       ...       ...       ...
1     776   0.879016 -0.156590 -0.142117  ...  0.066353  0.281378 -0.257966
      1129  0.269083  0.140631  0.023464  ... -0.179545 -0.192036 -0.261879
      905  -2.537387  1.391657 -2.770089  ...  0.517232 -0.035049 -0.465211
      896   0.086781 -0.202836  0.035154  ... -0.287592 -0.832682  0.128083
      1390  0.296319  0.139497 -0.123050  ... -0.128758 -0.381932  0.151012

                 V24       V25       V26       V27       V28  Amount  Class
Class
0     211  -0.253242  0.299379 -0.032755  0.017927  0.035667  169.00      0
      446   0.042338  0.720315 -0.332043  0.009356  0.014457   36.71      0
      732  -1.557907  0.059606  1.306595 -0.392186 -0.521429  206.77      0
      757   0.113747  0.412081  0.371214 -0.026679  0.023272    0.76      0
      66    0.716064 -0.602311 -0.064230 -0.315058 -0.272463    0.75      0
...              ...       ...       ...       ...       ...     ...    ...
1     776   0.385384  0.391117 -0.453853 -0.104448 -0.125765    1.00      1
      1129 -0.237477 -0.335040  0.240323 -0.345129 -0.383563    1.00      1
      905   0.320198  0.044519  0.177840  0.261145 -0.143276    0.00      1
      896   0.339427  0.215944  0.094704 -0.023354  0.030892    2.69      1
      1390 -1.363967 -1.389079  0.075412  0.231750  0.230171    0.99      1

[768 rows x 31 columns]

In [21]:
#4

# Cluster sampling
import numpy as np

from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=10, random_state=42).fit(new_data)
cluster_assignments = kmeans.labels_

n4 = int((1.96**2 * 0.5*0.5)/((0.05/10)**2))

# Select the clusters you want to include in the sample
selected_clusters = [0, 2, 4, 5, 8]

cluster_series = pd.Series(cluster_assignments)

# Create the new DataFrame containing only the rows from the selected clusters
cluster_sample = new_data[cluster_series.isin(selected_clusters)]

# Print the resulting DataFrame
(cluster_sample)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
137,85,1.327884,-0.735012,1.502449,-0.544105,-1.909350,-0.712498,-1.292820,-0.002715,-0.246028,...,0.461092,1.308647,-0.046031,0.764375,0.281841,-0.063753,0.060406,0.037296,11.99,0
140,88,1.287226,-0.824683,1.346423,-0.525628,-1.833007,-0.477715,-1.224213,0.014774,-0.257813,...,-0.147633,0.057765,0.052105,0.428755,-0.036979,1.112152,-0.003678,0.031920,30.90,0
142,89,-0.589856,0.933070,-0.268073,0.125245,2.396992,3.877945,0.189985,0.960389,-0.230000,...,-0.154397,-0.174834,-0.201369,1.013439,0.194412,-0.231765,0.541147,0.255374,37.13,0
143,91,1.276134,0.211470,0.143001,0.370050,0.154748,-0.032255,-0.003030,-0.038887,0.030715,...,-0.279654,-0.747704,0.056808,-0.759464,0.271641,0.174757,-0.010770,0.008104,1.98,0
144,91,-1.822273,1.235336,-0.307804,-1.821824,2.762482,3.641499,-0.344614,-1.547541,-0.138239,...,2.080848,-1.591888,0.321636,0.889258,0.156445,-0.960611,-0.035302,0.182321,15.89,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1518,539,-1.738582,0.052740,1.187057,-0.656652,0.920623,-0.291788,0.269083,0.140631,0.023464,...,-0.179545,-0.192036,-0.261879,-0.237477,-0.335040,0.240323,-0.345129,-0.383563,1.00,1
1519,118,1.254914,0.350287,0.302488,0.693114,-0.371470,-1.070256,0.086781,-0.202836,0.035154,...,-0.287592,-0.832682,0.128083,0.339427,0.215944,0.094704,-0.023354,0.030892,2.69,1
1520,574,1.257719,0.364739,0.306923,0.690638,-0.357792,-1.067481,0.094272,-0.210300,0.014455,...,-0.286856,-0.820658,0.127663,0.343128,0.221120,0.094391,-0.022189,0.030944,1.29,1
1522,484,-0.928088,0.398194,1.741131,0.182673,0.966387,-0.901004,0.879016,-0.156590,-0.142117,...,0.066353,0.281378,-0.257966,0.385384,0.391117,-0.453853,-0.104448,-0.125765,1.00,1
1525,539,-1.738582,0.052740,1.187057,-0.656652,0.920623,-0.291788,0.269083,0.140631,0.023464,...,-0.179545,-0.192036,-0.261879,-0.237477,-0.335040,0.240323,-0.345129,-0.383563,1.00,1

In [14]:
#5

# Convenience sampling
n5 = int((1.96**2 * 0.5*0.5)/((0.05)**2))
convenience_sample = pd.concat([new_data.head(380), new_data.tail(380)])
convenience_sample

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
2,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
3,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
4,2,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,...,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1521,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,1
1522,484,-0.928088,0.398194,1.741131,0.182673,0.966387,-0.901004,0.879016,-0.156590,-0.142117,...,0.066353,0.281378,-0.257966,0.385384,0.391117,-0.453853,-0.104448,-0.125765,1.00,1
1523,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,1
1524,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,1
1525,539,-1.738582,0.052740,1.187057,-0.656652,0.920623,-0.291788,0.269083,0.140631,0.023464,...,-0.179545,-0.192036,-0.261879,-0.237477,-0.335040,0.240323,-0.345129,-0.383563,1.00,1

Applying different Machine Learning Models to the above created samples.

In [18]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import ExtraTreesClassifier

model1 = LogisticRegression(random_state=42,max_iter=500)
model2 = DecisionTreeClassifier(random_state=42)
model3 = RandomForestClassifier(random_state=42)
model4 = SVC(random_state=42)
model5 = ExtraTreesClassifier(random_state=42)

# Define a dictionary to hold the sampling techniques and models
samplers = {
    'Sampling1': random_sample,
    'Sampling2': systematic_sample,
    'Sampling3': stratified_sample,
    'Sampling4': cluster_sample,
    'Sampling5': convenience_sample,
}
models = {
    'Model1': model1,
    'Model2': model2,
    'Model3': model3,
    'Model4': model4,
    'Model5': model5,
}

In [22]:
# Evaluate each model on each sampling technique

from sklearn.metrics import accuracy_score

results = {}
for sampler_name, sampler in samplers.items():
    if sampler_name == 'Sampling1':
        n = n1
    elif sampler_name == 'Sampling2':
        n = n2
    elif sampler_name == 'Sampling3':
        n = n3
    elif sampler_name == 'Sampling4':
        n = n4
    else:
        n = n5
    
    # Undersample or oversample the training data
    x_resampled, y_resampled = undersampler.fit_resample(x_train, y_train)
    
    # Limit the resampled data to the sample size
    if len(x_resampled) > n:
        x_resampled = x_resampled[:n]
        y_resampled = y_resampled[:n]
    
    for model_name, model in models.items():
        # Train the model on the resampled data
        model.fit(x_resampled, y_resampled)
        
        # Make predictions on the test data
        y_pred = model.predict(x_test)
        
        # Calculate the accuracy score
        accuracy = accuracy_score(y_test, y_pred)
        
        # Add the accuracy score to the results dictionary
        if model_name in results:
            results[model_name][sampler_name] = accuracy
        else:
            results[model_name] = {sampler_name: accuracy}

In [23]:
# Print the results
print('Results:')
print('        Sampling1   Sampling2   Sampling3   Sampling4   Sampling5')
for model_name, model_results in results.items():
    print(model_name, end='')
    for sampler_name in samplers.keys():
        if sampler_name in model_results:
            print(f'    {model_results[sampler_name]:.4f}   ', end='')
        else:
            print('              ', end='')
    print()

Results:
        Sampling1   Sampling2   Sampling3   Sampling4   Sampling5
Model1    0.4194       0.6129       0.4645       0.5806       0.5935
Model2    0.3806       0.8516       0.6839       0.6194       0.5806
Model3    0.5613       0.6516       0.6258       0.7097       0.7226
Model4    0.6839       0.6387       0.6194       0.5935       0.6774
Model5    0.6129       0.6516       0.5935       0.5806       0.7484